
import java.awt.Component;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.geom.GeneralPath;
import java.util.Collection;
import javax.swing.JComponent;
import javax.swing.JSlider;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicSliderUI;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * Eine grafische Darstellung des MINT-Punktezaehlers
 * @author Joana Bergsiek
 * @version 1.3
 */
public class GUI extends javax.swing.JFrame {
    
    private final ArrayList<Aktivitaet> S1 = new ArrayList<>(); //Geltende Aktivitaeten; siehe initialisiereA3S1Combo und jButton1MouseClicked
    private final ArrayList<Aktivitaet> S2 = new ArrayList<>(); //Geltende Aktivitaeten; siehe initialisiereA3S2Combo und jButton1MouseClicked
    private final ArrayList<JComboBox> alleA3S1Boxen = new ArrayList<>();
    private final ArrayList<JComboBox> alleA3S2Boxen = new ArrayList<>();
    private final ArrayList<JSlider> alleA3S1Slider = new ArrayList<>();
    private final ArrayList<JSlider> alleA3S2Slider = new ArrayList<>();
    private final ArrayList<JLabel> alleA3S1Label = new ArrayList<>();
    private final ArrayList<JLabel> alleA3S2Label = new ArrayList<>();
    private final int startanzahlA3Boxen = 7;
    private Zertifikat zer;
    private final int[] reihenindexPuffer = new int[10000]; //siehe reiheHervorheben
    private TableRowSorter<TableModel> rowSorter;
    //Diese Aktivitaeten sind nicht in der S1 absolvierbar
    private final ArrayList<String> keineS1Aktivitaeten = new ArrayList<>(); 
    //Diese Aktivitaeten sind nicht in der S2 absolvierbar
    private final ArrayList<String> keineS2Aktivitaeten = new ArrayList<>();  
    
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        initialisiereMeineElemente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jFrame1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jFrame1.setForeground(java.awt.Color.lightGray);
        jFrame1.setLocation(new java.awt.Point(0, 0));
        jFrame1.setSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPopupMenu1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jMenuItem1.setText("Aktivität SI hinzufügen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jMenuItem2.setText("Aktivität SII hinzufügen");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);
        jPopupMenu1.add(jSeparator1);

        jMenuItem3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jMenuItem3.setText("Alle A3-Aktivitäten löschen");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINTken Version 1.3 Joana Bergsiek");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Art der Aktivität", "Aktivität", "5 Punkte/ Niveau 1", "10 Punkte/ Niveau 2", "15 Punkte/ Niveau 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setName("Aktivitaetenliste"); // NOI18N
        jTable1.setRequestFocusEnabled(false);
        jTable1.setSelectionBackground(new java.awt.Color(157, 69, 73));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1280, 240));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 157, 69));
        jLabel1.setText("Anforderungsfeld II");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(157, 88, 69));
        jLabel2.setText("Anforderungsfeld III");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(69, 127, 157));
        jComboBox1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, 50));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 127, 157));
        jLabel3.setText("Anforderungsfeld I");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(93, 157, 69));
        jComboBox2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 380, 50));

        jSlider1.setMaximum(3);
        jSlider1.setMinimum(1);
        jSlider1.setValue(1);
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 127, 157));
        jLabel4.setText("Niveau: 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jSlider2.setMaximum(3);
        jSlider2.setMinimum(1);
        jSlider2.setValue(1);
        jSlider2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 157, 69));
        jLabel5.setText("Niveau: 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(157, 69, 73));
        jLabel6.setText("Erledigt in S I");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(157, 69, 73));
        jLabel7.setText("(Unter- und Mittelstufe)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(157, 107, 69));
        jLabel8.setText("S II");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(157, 107, 69));
        jLabel9.setText("(Oberstufe)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jLabel11.setText("Die Länge einer Spalte an den Grenzen im Header verändern. Durch Drag&Drop Spalten verschieben. Durch einen Klick auf eine Spalte Tabelle nach dieser alph. sortieren.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Auswertungsbutton.png"))); // NOI18N
        jButton1.setToolTipText("Auswertung");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(45, 40));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Speicherbutton.png"))); // NOI18N
        jButton2.setToolTipText("Auswertung als Datei speichern ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(45, 40));
        jButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton2StateChanged(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(157, 88, 69));
        jButton3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("?");
        jButton3.setToolTipText("Hilfe zum Anforderungsfeld");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(157, 149, 69));
        jButton4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("?");
        jButton4.setToolTipText("Was ist das MINT-Zertifikat?");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 20, -1, -1));

        jButton5.setBackground(new java.awt.Color(93, 157, 69));
        jButton5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("?");
        jButton5.setToolTipText("Hilfe zum Anforderungsfeld");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jButton6.setBackground(new java.awt.Color(69, 127, 157));
        jButton6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("?");
        jButton6.setToolTipText("Hilfe zum Anforderungsfeld");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jTextField1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jTextField1.setText(" Tabelle nach Wörtern filtern...");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(157, 69, 73), 2, true));
        jTextField1.setPreferredSize(new java.awt.Dimension(260, 24));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Ladebutton.png"))); // NOI18N
        jButton7.setToolTipText("Auswertung aus Datei laden");
        jButton7.setPreferredSize(new java.awt.Dimension(45, 40));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 20, -1, -1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(400, 360));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 360));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 1340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 400, -1));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(400, 360));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(400, 360));

        jPanel2.setMinimumSize(new java.awt.Dimension(400, 340));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane3.setViewportView(jPanel2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 400, -1));

        jButton8.setBackground(new java.awt.Color(157, 88, 69));
        jButton8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("+");
        jButton8.setToolTipText("Auswahlbox für SI hinzufügen");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setPreferredSize(new java.awt.Dimension(40, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 40, -1));

        jButton9.setBackground(new java.awt.Color(157, 107, 69));
        jButton9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("+");
        jButton9.setToolTipText("Auswahlbox für SII hinzufügen");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setPreferredSize(new java.awt.Dimension(40, 30));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt, JSlider slider) {
        String text = "Niveau: " + String.valueOf(slider.getValue());
        int index = 0;
        if (alleA3S1Slider.contains(slider)) {
            index = alleA3S1Slider.indexOf(slider);
            alleA3S1Label.get(index).setText(text);
        } else {
            index = alleA3S2Slider.indexOf(slider);
            alleA3S2Label.get(index).setText(text);
        }
    }
    
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        String text = "Niveau: " + String.valueOf(jSlider1.getValue());
        jLabel4.setText(text);
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        String text = "Niveau: " + String.valueOf(jSlider2.getValue());
        jLabel5.setText(text);
    }//GEN-LAST:event_jSlider2StateChanged

    /**
     * return true wenn die Daten des Nutzers fehlerhaft waren, false wenn ein erfolgreiches Zertifikat berechnet wurde 
     */
    private boolean werteDatenAus() {
        //Erstelle neues Zertifikat, damit sich jComboBox'en bei einer Aenderung der Wahl nicht draufaddieren
        zer = new Zertifikat();
        
        ArrayList<String> aktivNamen = new ArrayList<>();
        boolean fertig = false;
        ArrayList<JComboBox> alleA3Boxen = new ArrayList<>();
        alleA3Boxen.addAll((Collection<? extends JComboBox>) alleA3S1Boxen.clone());
        alleA3Boxen.addAll((Collection<? extends JComboBox>) alleA3S2Boxen.clone());
        
        ArrayList<JSlider> alleA3Slider = new ArrayList<>();
        alleA3Slider.addAll((Collection<? extends JSlider>) alleA3S1Slider.clone());
        alleA3Slider.addAll((Collection<? extends JSlider>) alleA3S2Slider.clone());
        
        //Pruefe zunaechst alle Felder....
        for (int i=0; i<alleA3Boxen.size();i++) {
            String akA1 = jComboBox1.getSelectedItem().toString();
            String akA2 = jComboBox2.getSelectedItem().toString();
            String akA3 = alleA3Boxen.get(i).getSelectedItem().toString();
            
            
            if (akA2.equals("Fachwissenschaftliche Arbeit mit mind. 10 Seiten") && akA3.equals("Fachwissenschaftliche Arbeit mit mindestens 10 Seiten oder besondere Lernleistung (Falls noch nicht in Anforderungsfeld I oder II eingebracht)")) {
                JOptionPane.showMessageDialog(jFrame1, "Wissenschaftliche Arbeit bereits in A2 eingetragen.");
                fertig = true;
                break;
            } else if (akA2.equals("Besondere Lernleistung") && akA3.equals("Fachwissenschaftliche Arbeit mit mindestens 10 Seiten oder besondere Lernleistung (Falls noch nicht in Anforderungsfeld I oder II eingebracht)")) {
                JOptionPane.showMessageDialog(jFrame1, "Besondere Lernleistung bereits in A2 eingetragen.");
                fertig = true;
                break;
            } else if (akA2.equals("Wissenschaftspropädeutisches Fach") && akA3.equals("wissenshaftspropädeutisches Fach oder zusätzlicher MINT-Kurs durchgängig in der Qualifikationsphase belegt (Falls noch nicht in Anforderungsfeld I oder II eingebracht)")) {
                JOptionPane.showMessageDialog(jFrame1, "Wissenschaftspropädeutisches Fach bereits in A2 eingetragen.");
                fertig = true;
                break;
            } else if(aktivNamen.contains(akA3) && !akA3.equals("Bitte wähle eine Aktivität des Anforderungsfeldes III")) {
                int currentSliderValue = alleA3Slider.get(i).getValue();
                if(i >= alleA3S1Boxen.size()) { //S2-jComboBox
                    Aktivitaet ausgewaehltS2 = S2.get(alleA3Boxen.get(i).getSelectedIndex()-1 ); //Index -1 weil das erste Objekt in der Auswahlliste immer "Bitte waehle..." ist
                    if (ausgewaehltS2.isMehrfachWertbar() == false) {
                        JOptionPane.showMessageDialog(jFrame1, new String[] {akA3 + " kann einmalig entweder in der S I oder der S II einberechnet werden.","Um Fehler in der Berechnung zu vermeiden, bitte entscheide dich für eine Bewertung der Aktivität.", "Es empfiehlt sich, die höher bewertete einzubeziehen."} );
                        fertig = true;
                        break;
                    }
                } else { //S1-jCombobox
                    Aktivitaet ausgewaehltS1 = S1.get(alleA3Boxen.get(i).getSelectedIndex()-1 ); //Index -1 weil das erste Objekt in der Auswahlliste immer "Bitte waehle..." ist
                    if (ausgewaehltS1.isMehrfachWertbar() == false) {
                        JOptionPane.showMessageDialog(jFrame1, new String[] {akA3 + " kann einmalig entweder in der S I oder der S II einberechnet werden.","Um Fehler in der Berechnung zu vermeiden, bitte entscheide dich für eine Bewertung der Aktivität.", "Es empfiehlt sich, die höher bewertete einzubeziehen."} );
                        fertig = true;
                        break;
                    }
                }
            } 
            //Kein Ausnahmefall, die Schleife musste nicht angehalten werden
            if (!akA3.equals("Bitte wähle eine Aktivität des Anforderungsfeldes III")) { //Der Benutzer hat eine Aktivitaet ausgewaehlt
                int currentSliderValue = alleA3Slider.get(i).getValue();
                if(i >= alleA3S1Boxen.size()) { //S2-jComboBox
                    Aktivitaet ausgewaehltS2 = S2.get(alleA3Boxen.get(i).getSelectedIndex()-1 ); //Index -1 weil das erste Objekt in der Auswahlliste immer "Bitte waehle..." ist
                    if(ausgewaehltS2.getAnforderung(currentSliderValue-1).equals("")) { //siehe naechste Zeile
                        JOptionPane.showMessageDialog(jFrame1, "Das ausgewählte Niveau der Aktivität " + akA3 + " ist nicht verfügbar.");
                        fertig = true;
                        break;
                    }
                    zer.getAnforderungsfeldDrei().aktivitaetErfuelltS2(ausgewaehltS2, currentSliderValue);
                } else { //S1-jCombobox
                    Aktivitaet ausgewaehltS1 = S1.get(alleA3Boxen.get(i).getSelectedIndex()-1 ); //Index -1 weil das erste Objekt in der Auswahlliste immer "Bitte waehle..." ist
                    if(ausgewaehltS1.getAnforderung(currentSliderValue-1).equals("")) { //siehe naechste Zeile
                        JOptionPane.showMessageDialog(jFrame1, "Das ausgewählte Niveau der Aktivität " + akA3 + " ist nicht verfügbar.");
                        fertig = true;
                        break;
                    }
                    
                    zer.getAnforderungsfeldDrei().aktivitaetErfuelltS1(ausgewaehltS1, currentSliderValue);
                }
            }
            aktivNamen.add(akA3);
            
        } 
        
        if (fertig == true) {
            //Die Schleife musste wegen einer Fehlermeldung abgebrochen werden, mache nichts mehr
        } else {
            //Jetzt noch die Anforderungsfelder I & II
            if (!jComboBox1.getSelectedItem().toString().equals("Bitte wähle eine Aktivität des Anforderungsfeldes I")) { //Der Benutzer hat eine Aktivitaet ausgewaehlt
                zer.getAnforderungsfeldEins().aktivitaetErfuellt(zer.getAnforderungsfeldEins().getErfuellbareAktivitaeten().get(jComboBox1.getSelectedIndex()-1), jSlider1.getValue());
            }
        
            if (!jComboBox2.getSelectedItem().toString().equals("Bitte wähle eine Aktivität des Anforderungsfeldes II")) { //Der Benutzer hat eine Aktivitaet ausgewaehlt
                zer.getAnforderungsfeldZwei().aktivitaetErfuellt(zer.getAnforderungsfeldZwei().getErfuellbareAktivitaeten().get(jComboBox2.getSelectedIndex()-1), jSlider2.getValue());
            }
            zer.aktualisiereAlle();
        }
        return fertig;
    }
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            if (werteDatenAus() == false) {
                //Der Beratungstext
                String[] beratungstext = zer.berate().split(" _// "); //Teilung des Textes zwischen den einzelnen Anforderungsfeldern
            
                //Ergebnis ausgeben
                JOptionPane.showMessageDialog(jFrame1, beratungstext);
            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton2StateChanged
        
    }//GEN-LAST:event_jButton2StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            if (werteDatenAus()== false) {
                //Erzeuge ein Dialogfenster, damit der Nutzer selbststaendig den Dateipfad
                //und -namen seiner Auswertung bestimmen kann
                JFileChooser jFileChooser1 = new JFileChooser();
                jFileChooser1.setDialogTitle("MINTken-Auswertung speichern");
                FileNameExtensionFilter filter = new FileNameExtensionFilter(".txt", "txt", "text");
                jFileChooser1.setFileFilter(filter);
                jFileChooser1.showSaveDialog(this);
                String dateiname = jFileChooser1.getToolTipText();
                jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
                try {
                    //Versuche die Datei unter gegebenen Namen zu speichern
                    zer.erfuellteAktivitaetenTextdatei(jFileChooser1.getSelectedFile().getAbsolutePath());
                    JOptionPane.showMessageDialog(jFrame1, "Datei wurde im ausgewählten Pfad gespeichert." );
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(jFrame1, "Speichern der Datei fehlgeschlagen oder fehlerhaft." );
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Knopf fuer Beschreibung des Zertifikats
        String text = String.format("Das MINT-EC-Zertifikat wird auf Antrag des Schülers zusammen mit dem Abiturzeugnis an Schülerinnen und Schüler vergeben, die im Laufe ihrer\n"
                + "Schulzeit kontinuierlich über den Unterricht hinaus besondere Leistungen in den MINT-Fächern (Mathematik, Informatik, Naturwissenschaften, Technik) erbracht haben.\n"
                + "Die Kontrolle der Aktivitäten erfolgt durch Kopien von Urkunden, Zeugnissen etc., die beim MINT-Koordinator abgegeben werden müssen. \n \n"
                + "Schülerinnen und Schüler, die das MINT-EC-Zertifikat erhalten, müssen Mindestanforderungen in den drei Anforderungsfeldern\n" +
                   String.format("%36s ", "") + "I 	 Fachliche Kompetenz\n" +
                   String.format("%36s ", "") +"II 	 Fachwissenschaftliches Arbeiten\n" +
                   String.format("%36s ", "") +"III  Zusätzliche MINT-Aktivitäten erfüllen.\n \n"
                   + "In jedem der drei Anforderungsfelder werden die Schülerleistungen einer der drei Stufen\n" +
                   String.format("%36s ", "") +"1 	 „mit Erfolg“\n" +
                   String.format("%36s ", "") +"2 	 „mit besonderem Erfolg“\n" +
                   String.format("%36s ", "") +"3 	 „mit Auszeichnung“ zugeordnet\n \n"
                + "Ein Zertifikat wird nur verliehen, wenn in jedem der drei Felder mindestens die Stufe 1 erreicht wurde.\n" + 
                   "Die Gesamteinstufung des Zertifikates ergibt sich aus dem mathematisch gerundeten Mittelwert der in den drei Anforderungsfeldern erreichten Stufen.\n" +
                   "Das MINT-EC-Zertifikat wird in Form einer vierseitigen Urkunde verliehen.\n" );
 
                                
        JOptionPane.showMessageDialog(jFrame1, text );
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Knopf fuer A2
        String hilfetext[] = {zer.getAnforderungsfeldZwei().getFokus(), 
                                " ",
                                "Anforderung für Stufe 1: >= 9 Notenpunkte.",
                                "Anforderung für Stufe 2: >= 11 Notenpunkte.",
                                "Anforderung für Stufe 3: >= 13 Notenpunkte.",
                                " ",
                                "Wenn Einbeziehung einer der möglichen Wettbewerbe: ",
                                "Anforderung für Stufe 1: Ernsthafte Teilnahme am Regionalwettbewerb.",
                                "Anforderung für Stufe 2: Preisträger im Regionalwettbewerb (keine Sonderpreise).",
                                "Anforderung für Stufe 3: Teilnahme am Landes- oder Bundeswettbewerb."};
        JOptionPane.showMessageDialog(jFrame1, hilfetext );
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Knopf fuer A3
        String hilfetext[] = {zer.getAnforderungsfeldDrei().getFokus(),
                                " ",
                                "Anforderung für Stufe 1: Ab 40 Punkte, davon maximal 20 aus der SI.",
                                "Anforderung für Stufe 2: Ab 60 Punkte, davon maximal 30 aus der SI UND mindestens einmal Niveau 2 in der SII.",
                                "Anforderung für Stufe 3: Ab 80 Punkte, davon maximal 40 aus der SI UND mindestens zweimal Niveau 2 in der SII",
                                String.format("%36s ", "") + "ODER 80 Punkte, davon maximal 40 aus der SI UND einmal Niveau 3 in der SII.",
                                " ",
                                "Eine Aktivität kann entweder durch einer der Boxen oder direkt aus der Tabelle mit einem Rechtsklick hinzugefügt werden."};
        JOptionPane.showMessageDialog(jFrame1, hilfetext );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboBoxStateChange(java.awt.event.ItemEvent evt, JComboBox box) {
        reiheHervorheben(box);
    }
    
    private void comboBoxFocusGained (java.awt.event.FocusEvent evt, JComboBox box) {
        reiheHervorheben(box);
    } 
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Knopf fuer A1
        String hilfetext[] = {zer.getAnforderungsfeldEins().getFokus(), 
                                " ",
                                "Anforderung für Stufe 1: Mittelwert aller anzurechnender Kurse >= 9 Notenpunkte.",
                                "Anforderung für Stufe 2: Mittelwert aller anzurechnender Kurse >= 11 Notenpunkte.",
                                "Anforderung für Stufe 3: Mittelwert aller anzurechnender Kurse >= 13 Notenpunkte.",
                                " ",
                                "Dabei müssen die Kurse durchgehend in der Qualifikationsphase belegt worden sein und die Punkte eines anzurechnenden Kurses dürfen nicht unter 5 liegen.",
                                "Das Ergebnis darf nicht gerundert werden (Beispiel: 12,75 Punkte -> Stufe 2 )"};
        JOptionPane.showMessageDialog(jFrame1, hilfetext );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        if (SwingUtilities.isRightMouseButton(evt)) {
            //Wechsel den Fokus
            jTable1.requestFocusInWindow();
            //Markiere die angeklickte Aktivitaet
            Point p = evt.getPoint(); //Kriege die Koordinaten vom Mausklick
            int reihenIndex = jTable1.rowAtPoint(p); //Die Reihe, die die Koordinate enthaelt
            jTable1.setRowSelectionInterval(reihenIndex, reihenIndex);

            //Setze das Menue auf Startzustand
            jPopupMenu1.removeAll();

            //Fuege die Auswahlmoeglichkeiten hinzu
            jPopupMenu1.add(jMenuItem1);
            jPopupMenu1.add(jMenuItem2);
            jPopupMenu1.add(jSeparator1);
            jPopupMenu1.add(jMenuItem3);

            //Zeige das Menue an
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Welche Aktivitaet wurde markiert?
        int reihenIndex = jTable1.getSelectedRow();
        String aktivitaet = jTable1.getValueAt(reihenIndex, 1).toString();

        if (keineS1Aktivitaeten.contains(aktivitaet)) { //ungueltige Aktivitaet; siehe naechste Zeile
            JOptionPane.showMessageDialog(jFrame1, "Diese Aktivität lässt sich nicht in der SI absolvieren.");
        } else { //gueltige Aktivitaet
            //Gehe die Comboboxen der SI durch, um zu schauen, ob fuer jede bereits jeweils eine Aktivitaet ausgewaehlt wurde.
            //Fuege wenn moeglich die Aktivitaet zu der erstgefundensten unausgewaehlten Box hinzu.
            //Sonst fuege eine Auswahlbox mit der Aktivitaet hinzu.
            for (int i = 0; i <= alleA3S1Boxen.size(); i++) {
                if (alleA3S1Boxen.get(i).getSelectedItem().equals("Bitte wähle eine Aktivität des Anforderungsfeldes III")) { //Eine Box ohne ausgewaehlte Aktivitaet
                    alleA3S1Boxen.get(i).setSelectedItem(aktivitaet);
                    alleA3S1Slider.get(i).requestFocusInWindow();
                    break;
                }
                if (i == alleA3S1Boxen.size()-1) { 
                    fuegeA3S1SetHinzu();
                    alleA3S1Boxen.get(i+1).setSelectedItem(aktivitaet);
                    alleA3S1Slider.get(i+1).requestFocusInWindow();
                    jScrollPane2.getVerticalScrollBar().setValue(jScrollPane2.getVerticalScrollBar().getMaximum());
                    break;
                }
            }
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Welche Aktivitaet wurde markiert?
        int reihenIndex = jTable1.getSelectedRow();
        String aktivitaet = jTable1.getValueAt(reihenIndex, 1).toString();

        if (keineS2Aktivitaeten.contains(aktivitaet)) {
            JOptionPane.showMessageDialog(jFrame1, "Diese Aktivität lässt sich nicht in der SII absolvieren.");
        } else {
            //Gehe die Comboboxen der SII durch, um zu schauen, ob fuer jede bereits jeweils eine Aktivitaet ausgewaehlt wurde.
            //Fuege wenn moeglich die Aktivitaet zu der erstgefundensten unausgewaehlten Box hinzu.
            //Sonst gebe eine Meldung aus, dass alle Boxen bereits eine Aktivitaet ausgewaehlt haben.
            for (int i = 0; i < alleA3S2Boxen.size(); i++) {
                if (alleA3S2Boxen.get(i).getSelectedItem().equals("Bitte wähle eine Aktivität des Anforderungsfeldes III")) { //Eine Box ohne ausgewaehlte Aktivitaet
                    alleA3S2Boxen.get(i).setSelectedItem(aktivitaet);
                    alleA3S2Slider.get(i).requestFocusInWindow();
                    break;
                }
                if (i == alleA3S2Boxen.size()-1) { 
                    fuegeA3S2SetHinzu();
                    alleA3S2Boxen.get(i+1).setSelectedItem(aktivitaet);
                    alleA3S2Slider.get(i+1).requestFocusInWindow();
                    jScrollPane3.getVerticalScrollBar().setValue(jScrollPane3.getVerticalScrollBar().getMaximum());
                    break;
                }
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        leereAlleA3Boxen();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        //Code siehe http://stackoverflow.com/a/22067320
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jTextField1.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jTextField1.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("");
            }
        });
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        //Das Textfield wurde erstmalig ausgewaehlt
        if(jTextField1.getText().equals(" Tabelle nach Wörtern filtern...")) {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Erzeuge den FileChooser
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.setDialogTitle("MINTken-Auswertung Laden");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".txt", "txt", "text");
        jFileChooser1.setFileFilter(filter);
        jFileChooser1.showOpenDialog(this);
        String dateiname = jFileChooser1.getSelectedFile().getAbsolutePath();
        if (!dateiname.endsWith(".txt")) {
            JOptionPane.showMessageDialog(jFrame1, "Es können nur Textdateien (.txt) ausgelesen werden." );
        }
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        
        try {
            //Erhalte die Codes aus der Datei und fuege die Aktivitaeten dem Zertifikat hinzu
            ArrayList<String> codes = zer.erhalteCodesAusDatei(dateiname);
            if (codes.isEmpty()) {
                JOptionPane.showMessageDialog(jFrame1, "Es wurde eine ungültige MINTken-Auswertungsdatei ausgewählt. \n"
                        + "\n"
                        + "Für eine gültige Datei müssen vor der Aktivitätenaufzählung am Schluss jeweils 5-stellige Codes stehen.");
            }
            leereAlleA3Boxen();
            zer = new Zertifikat();
            zer.erzeugeZertfikatsdaten(codes);
            
            //A1-Box & Regler einstellen
            if (!zer.getAnforderungsfeldEins().erfuellteAktivitaeten.isEmpty()) {
                jComboBox1.setSelectedItem(zer.getAnforderungsfeldEins().erfuellteAktivitaeten.get(0).getName());
                jSlider1.setValue(zer.getAnforderungsfeldEins().erfuellteAktivitaeten.get(0).getNiveau());
            }
            
            
            //A2-Box & Regler einstellen
            if (!zer.getAnforderungsfeldZwei().erfuellteAktivitaeten.isEmpty()) {
                jComboBox2.setSelectedItem(zer.getAnforderungsfeldZwei().erfuellteAktivitaeten.get(0).getName());
                jSlider2.setValue(zer.getAnforderungsfeldZwei().erfuellteAktivitaeten.get(0).getNiveau());
            }
            
            //A3S1-Boxen & Regler einstellen
            for (int i = 0 ; i < zer.getAnforderungsfeldDrei().getErfuellteAktivitaetenS1().size(); i++) {
                if (i >= alleA3S1Boxen.size()) {
                    fuegeA3S1SetHinzu();
                }
                alleA3S1Boxen.get(i).setSelectedItem(zer.getAnforderungsfeldDrei().getErfuellteAktivitaetenS1().get(i).getName());
                alleA3S1Slider.get(i).setValue(zer.getAnforderungsfeldDrei().getErfuellteAktivitaetenS1().get(i).getNiveau());
            }
            
            //A3S2-Boxen & Regler einstellen
            for (int i = 0 ; i < zer.getAnforderungsfeldDrei().getErfuellteAktivitaetenS2().size(); i++) {
                if (i >= alleA3S2Boxen.size()) {
                    fuegeA3S2SetHinzu();
                }
                alleA3S2Boxen.get(i).setSelectedItem(zer.getAnforderungsfeldDrei().getErfuellteAktivitaetenS2().get(i).getName());
                alleA3S2Slider.get(i).setValue(zer.getAnforderungsfeldDrei().getErfuellteAktivitaetenS2().get(i).getNiveau());
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(jFrame1, "Laden der Datei fehlgeschlagen oder fehlerhaft." );
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        fuegeA3S1SetHinzu();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        fuegeA3S2SetHinzu();
    }//GEN-LAST:event_jButton9ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    /**
     * Setze alle A3-Boxen und ihre Regler auf Anfangszustand
     */
    public void leereAlleA3Boxen() {
        for (int i = 0; i < alleA3S1Boxen.size(); i++) {
            alleA3S1Boxen.get(i).setSelectedItem("Bitte wähle eine Aktivität des Anforderungsfeldes III");
            alleA3S1Slider.get(i).setValue(1);
        }
        for (int i = 0; i < alleA3S2Boxen.size(); i++) {
            alleA3S2Boxen.get(i).setSelectedItem("Bitte wähle eine Aktivität des Anforderungsfeldes III");
            alleA3S2Slider.get(i).setValue(1);
        }
    }
    
    /**
     * Hebt die Reihe einer ausgewaehlten Aktivitaet hervor, indem sie markiert wird und ggf. an erster Stelle steht 
     */
    private void reiheHervorheben(JComboBox box) {
        String ausgewaehlteAkt = box.getSelectedItem().toString(); 
        int ausgewaehlteBox = 0;
        if (alleA3S1Boxen.contains(box)) {
            ausgewaehlteBox = alleA3S1Boxen.indexOf(box);
        } else {
            ausgewaehlteBox = alleA3S2Boxen.indexOf(box) + alleA3S2Boxen.size();
        }
        
        if(ausgewaehlteAkt.equals("Bitte wähle eine Aktivität des Anforderungsfeldes III")) { //Der Nutzer hat die Komponente zurueck auf den Anfangszustand gesetzt, also keine Aktivitaet
            //Loesche alte Auswahl
            int alteReiheIndex = reihenindexPuffer[ausgewaehlteBox+1];
            jTable1.removeRowSelectionInterval(alteReiheIndex, alteReiheIndex);
        }
        
        for (int i=0; i<jTable1.getRowCount(); i++) {
            String ausgewaehlteReihe = jTable1.getValueAt(i, 1).toString();
            if (ausgewaehlteAkt.equals(ausgewaehlteReihe)) {
                jTable1.setRowSelectionInterval(i, i); //markiere ausgewaehlte Akitivitaet in der Liste
                jTable1.scrollRectToVisible(new Rectangle(jTable1.getCellRect(i, 0, true))); //autoscrolle zu der Aktivitaet, so dass diese immer nach dem Auswaehlen sichtbar ist
                reihenindexPuffer[ausgewaehlteBox+1] = i;
            }
        }
    }
    
    
    /**
     * Fuellt die Tabelle mit den Aktivitaeten.
     */
    private void initalisiereJTable() {
        ArrayList<Aktivitaet> taeten = zer.getAnforderungsfeldDrei().getErfuellbareAktivitaeten();
        int aktisize = taeten.size();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for (int reihe=0; reihe<aktisize; reihe++) {
            if (zer.getAnforderungsfeldDrei().getErfuellbareAktivitaeten().get(reihe).isIstWettbewerb() == true) { //Die Aktivitaet ist ein Wettbewerb
                Object[] aktiDaten = {"Wettbewerb", taeten.get(reihe).getName(), taeten.get(reihe).getAnforderung(0), taeten.get(reihe).getAnforderung(1), taeten.get(reihe).getAnforderung(2)}; //Alle Aktivitaetsdaten fuer eine Reihe
                model.addRow(aktiDaten);
            } else { //Die Aktivitaet ist kein Wettbewerb
                Object[] aktiDaten = {"Lehr- und Lernveranstaltungen", taeten.get(reihe).getName(), taeten.get(reihe).getAnforderung(0), taeten.get(reihe).getAnforderung(1), taeten.get(reihe).getAnforderung(2)}; //Alle Aktivitaetsdaten fuer eine Reihe
                model.addRow(aktiDaten);
            }
        }
    }
    
    /**
     * Fasst die Initialisation der hinzugefuegten Komponenten zusammen.
     */
    private void initialisiereMeineElemente() {
        zer = new Zertifikat();
        initialisiereSpeziallisten();
        initalisiereJTable();
        initialisiereAlleCombo();
        for (int i = 0; i < startanzahlA3Boxen; i++) {
            fuegeA3S1SetHinzu();
            fuegeA3S2SetHinzu();
        }
        setzeIcon();
        aendereThumbs();
        jTable1.getTableHeader().setDefaultRenderer(new HeaderColor()); 
        this.rowSorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(rowSorter);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(10);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(10);
    }
    
    /**
     * Fasst die Neuinitialisierung der JSlider thumbs zusammen
     */
    private void aendereThumbs() {
        jSlider1.setUI(new CustomSliderUI(jSlider1,69,127,157)); //blau
        jSlider2.setUI(new CustomSliderUI(jSlider2,93,157,69)); //gruen
    }
    
    /**
     * Fasst die Initialisierung aller ComboBox'en zusammen
     */
    private void initialisiereAlleCombo() {
        initialisiereA1Combo();
        initialisiereA2Combo();
    }
    
    /**
     * Fuellt die Listen keineS1Aktivitaeten und keineS2Aktivitaeten welche jeweils die Aktivitaeten beherbergen, welche nicht in der jeweiligen Stufe erfuellbar sind.
     */
    private void initialisiereSpeziallisten() {
        for (Aktivitaet erfuellbareAktivitaeten : zer.getAnforderungsfeldDrei().erfuellbareAktivitaeten) {
            switch(erfuellbareAktivitaeten.getErfuellbarFuer()) {
                case 1: //Die momentane Aktivitaet ist nur in der SI erfuellbar
                    keineS2Aktivitaeten.add(erfuellbareAktivitaeten.getName());
                    break;
                case 2: //Die momentane Aktivitaet ist nur in der SII erfuellbar
                    keineS1Aktivitaeten.add(erfuellbareAktivitaeten.getName());
                    break;
                default: //Die momentane Aktivitaet kann in beiden Stufen erfuellt werden
                    break;
            }
        }
    }
    
    /**
     * Fuellt die ComboBox mit den Aktivitaeten des Anforderungsfeldes 1
     */
    private void initialisiereA1Combo() {
        jComboBox1.addItem("Bitte wähle eine Aktivität des Anforderungsfeldes I");
        for (Aktivitaet erfuellbareAktivitaeten : zer.getAnforderungsfeldEins().erfuellbareAktivitaeten) {
            jComboBox1.addItem(erfuellbareAktivitaeten.getName());
        }
        adjustScrollBar(jComboBox1);
    }
    
    /**
     * Fuellt die ComboBox mit den Aktivitaeten des Anforderungsfeldes 2
     */
    private void initialisiereA2Combo() {
        jComboBox2.addItem("Bitte wähle eine Aktivität des Anforderungsfeldes II");
        for (Aktivitaet erfuellbareAktivitaeten : zer.getAnforderungsfeldZwei().erfuellbareAktivitaeten) {
            jComboBox2.addItem(erfuellbareAktivitaeten.getName());
        }
        adjustScrollBar(jComboBox2);
    }
    
    /**
     * Fuellt die ComboBox der S1 mit den Aktivitaeten des Anforderungsfeldes 3
     */
    private void initialisiereA3S1Combo(JComboBox box) {
        box.addItem("Bitte wähle eine Aktivität des Anforderungsfeldes III");
        for (Aktivitaet erfuellbareAktivitaeten : zer.getAnforderungsfeldDrei().erfuellbareAktivitaeten) {
            if ((keineS1Aktivitaeten.contains(erfuellbareAktivitaeten.getName()))) {
                //Die Aktivitaeten duerfen nicht in die JComboBox fuer die S1
            } else {
                box.addItem(erfuellbareAktivitaeten.getName());
                S1.add(erfuellbareAktivitaeten);
            }
        }
        adjustScrollBar(box);
    }
    
    /**
     * Fuellt die ComboBox der S2 mit den Aktivitaeten des Anforderungsfeldes 3
     */
    private void initialisiereA3S2Combo(JComboBox box) {
        box.addItem("Bitte wähle eine Aktivität des Anforderungsfeldes III");
        for (Aktivitaet erfuellbareAktivitaeten : zer.getAnforderungsfeldDrei().erfuellbareAktivitaeten) {
            if ((keineS2Aktivitaeten.contains(erfuellbareAktivitaeten.getName()))) {
            //Die Aktivitaeten duerfen nicht in die JComboBox fuer die S2
            } else {
                box.addItem(erfuellbareAktivitaeten.getName());
                S2.add(erfuellbareAktivitaeten);
            }
        }
        adjustScrollBar(box);
    }
    
    /**
     * Fuegt fuer S1 eine Box samt dazugehoerigen Regler&Reglertext hinzu
     */
    private void fuegeA3S1SetHinzu() {
        //Initialisiere die Box
        int yKoordBox = alleA3S1Boxen.size() * 50 ;
        alleA3S1Boxen.add(new javax.swing.JComboBox<>());
        final JComboBox box = alleA3S1Boxen.get(alleA3S1Boxen.size()-1);
        box.setBackground(new java.awt.Color(157, 69, 73));
        box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        box.setPreferredSize(new java.awt.Dimension(28, 35));
        box.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxStateChange(evt, box);
            }
        });
        box.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxFocusGained(evt, box);
            }
        });
        //Fuelle den Inhalt der Box
        initialisiereA3S1Combo(box);
        
        //Initialisiere Regler
        alleA3S1Slider.add(new javax.swing.JSlider());
        final JSlider regler = alleA3S1Slider.get(alleA3S1Slider.size()-1);
        regler.setMaximum(3);
        regler.setMinimum(1);
        regler.setValue(1);
        regler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regler.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt, regler);
            }
        });
        regler.setUI(new CustomSliderUI(regler,157,69,73)); 
        
        //Initialisiere dazugehoerigen Text
        int yKoordLabel = alleA3S1Label.size() * 50  + 20;
        alleA3S1Label.add(new javax.swing.JLabel());
        JLabel label = alleA3S1Label.get(alleA3S1Label.size()-1);
        label.setForeground(new java.awt.Color(157, 69, 73));
        label.setText("Niveau: 1");
        
        //Fuege alles dem Panel hinzu und passe die Ansicht an
        jPanel1.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, yKoordBox, 240, -1));
        jPanel1.add(regler, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, yKoordBox, 130, 20));
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, yKoordLabel, -1, -1));
        jScrollPane2.setViewportView(jPanel1);
    }
    
    /**
     * Fuegt fuer S1 eine Box samt dazugehoerigen Regler&Reglertext hinzu
     */
    private void fuegeA3S2SetHinzu() {
        //Initialisiere die Box
        int yKoordBox = alleA3S2Boxen.size() * 50;
        alleA3S2Boxen.add(new javax.swing.JComboBox<>());
        final JComboBox box = alleA3S2Boxen.get(alleA3S2Boxen.size()-1);
        box.setBackground(new java.awt.Color(157, 107, 69));
        box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        box.setPreferredSize(new java.awt.Dimension(28, 35));
        box.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxStateChange(evt, box);
            }
        });
        box.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxFocusGained(evt, box);
            }
        });
        //Fuelle den Inhalt der Box
        initialisiereA3S2Combo(box);
        
        //Initialisiere Regler
        alleA3S2Slider.add(new javax.swing.JSlider());
        final JSlider regler = alleA3S2Slider.get(alleA3S2Slider.size()-1);
        regler.setMaximum(3);
        regler.setMinimum(1);
        regler.setValue(1);
        regler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regler.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt, regler);
            }
        });
        regler.setUI(new CustomSliderUI(regler,157, 107, 69)); 
        
        //Initialisiere dazugehoerigen Text
        int yKoordLabel = alleA3S2Label.size() * 50  + 20;
        alleA3S2Label.add(new javax.swing.JLabel());
        JLabel label = alleA3S2Label.get(alleA3S2Label.size()-1);
        label.setForeground(new java.awt.Color(157, 107, 69));
        label.setText("Niveau: 1");
        
        //Fuege alles dem Panel hinzu und passe die Ansicht an
        jPanel2.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, yKoordBox, 240, -1));
        jPanel2.add(regler, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, yKoordBox, 130, 20));
        jPanel2.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, yKoordLabel, -1, -1));
        jScrollPane3.setViewportView(jPanel2);
    }
    
    
    
    /**
     * Fuegt den JComboBox'en horizontale Rollleisten hinzu.
     * @see https://community.oracle.com/thread/1775495?tstart=0
     * @param box Die JComboBox, die eine horizontale Rolleiste bekommen soll
     */
    private void adjustScrollBar(JComboBox box) {
        if (box.getItemCount() == 0) return;
        Object comp = box.getUI().getAccessibleChild(box, 0);
        if (!(comp instanceof JPopupMenu)) {
            return;
        }
        JPopupMenu popup = (JPopupMenu) comp;
        JScrollPane scrollPane = (JScrollPane) popup.getComponent(0);
        scrollPane.setHorizontalScrollBar(new JScrollBar(JScrollBar.HORIZONTAL));
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    }
    
    
    
    /**
     * Fuegt dem Programm ein individuelles Icon hinzu und ersetzt das Java-Icon 
     */
    private void setzeIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resource/icon.png")));
    }
    
    
    /**
     * Benutze einen Renderer, um die Farbe der Tabelle zu aendern (hier zu einem roten Hintergrund und weißer Schrift)
     */
    static public class HeaderColor extends DefaultTableCellRenderer {
        public HeaderColor() {
            setOpaque(true);
        }
        
        @Override
        public Component getTableCellRendererComponent (JTable mytable, Object value, boolean selected, boolean focus, int row, int column) {
            super.getTableCellRendererComponent(mytable, value, selected, focus, row, column);
            setBackground(new java.awt.Color(157,69,73)); //rot
            setForeground(new java.awt.Color(255, 255, 255)); //weiß
            return this;
        }
    }
    
    /**
    * Aendere das Aussehen des JSlider thumbs
    * @see http://stackoverflow.com/a/12297384/714968
    */
    public class CustomSliderUI extends BasicSliderUI {
        int color1;
        int color2;
        int color3;
        private BasicStroke stroke = new BasicStroke(1f, BasicStroke.CAP_ROUND, 
            BasicStroke.JOIN_ROUND, 0f, new float[]{1f, 2f}, 0f);

        public CustomSliderUI(JSlider b, int c1, int c2, int c3) {
            super(b);
            color1 = c1;
            color2 = c2;
            color3 = c3;
        }

        @Override
        public void paint(Graphics g, JComponent c) {
            Graphics2D g2d = (Graphics2D) g;
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, 
                RenderingHints.VALUE_ANTIALIAS_ON);
            super.paint(g, c);
        }

        @Override
        protected Dimension getThumbSize() {
            return new Dimension(15, 16);
        }
        
        @Override
        public void paintThumb(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int x1 = thumbRect.x + 2;
            int x2 = thumbRect.x + thumbRect.width - 2;
            int width = thumbRect.width - 4;
            int topY = thumbRect.y + thumbRect.height / 2 - thumbRect.width / 3;
            GeneralPath shape = new GeneralPath(GeneralPath.WIND_EVEN_ODD);
            shape.moveTo(x1, topY);
            shape.lineTo(x2, topY);
            shape.lineTo((x1 + x2) / 2, topY + width);
            shape.closePath();
            g2d.setPaint(new Color(color1,color2,color3));
            g2d.fill(shape);
            Stroke old = g2d.getStroke();
            g2d.setStroke(new BasicStroke(2f));
            g2d.setPaint(new Color(color1, color2, color3));
            g2d.draw(shape);
            g2d.setStroke(old);
        }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
    
}
